---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint

  - repo: local
    hooks:
      - id: yamllint
        name: Yamllint
        description: This hook runs yamllint.
        entry: yamllint .
        language: python
        types: [file, yaml]
