---
# Configuration: https://yamllint.readthedocs.io/en/stable/configuration.html
# Rules: https://yamllint.readthedocs.io/en/stable/rules.html

extends: default

rules:
  line-length:
    max: 110
    level: warning
  truthy: {check-keys: false}
